export { default as ToggleButtonComp } from './toggle/Toggle'
export { default as FooterPageBottom } from './footer/Footer'
export { default as HeaderLogoHead } from './logo/Logo'
export { default as LandingPageTitle } from './homeintro/HeroBigTitle'
export { default as JamStack } from './jam/JamTech'
export { default as JamWriting } from './goToWrite/IntroWrite'
