import Head from 'next/head'
import type { NextPage } from 'next'
import Text from 'components/text/Text'
import { motion } from 'framer-motion'

const FourOhFour: NextPage = () => {
  return (
    <>
      <Head>
        <title>4 Oh Four</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <motion.div
        style={{
          gap: '0.5rem',
          display: 'grid',
        }}
        variants={column}
        initial={'hidden'}
        animate={'visible'}>
        <Text
          size={48}
          variants={content}
          content='404 – Not all those who wander are lost.'
          color={'white'}
          weight={700}
          capitalize='first'
        />
        <Text
          size={16}
          color={'gray'}
          variants={content}
          content='Some beautiful paths can not be discovered without getting lost.'
        />
      </motion.div>
    </>
  )
}

const column = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
}

const content = {
  hidden: { opacity: 0, y: 50 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      type: 'jsut',
    },
  },
}

export default FourOhFour
